"use strict";

/*
 * TRIV101 — survey prompt pool
 * ------------------------------------------------------------------
 * These are the ~100 prompts players get SURVEYED on (via the "Take a Survey"
 * opt-in). They are deliberately separate from the game's active question bank
 * (questions.js / window.TRIV101_SEED): a prompt here collects real answers,
 * and only once its top 3 answers are confirmed (through moderation, in
 * production) does it graduate into the game bank.
 *
 * Family-Feud style, evergreen, crowd-answerable, bar/party-friendly. Edit
 * freely — add, cut, or retheme. No preset answers: the crowd supplies those.
 */

window.TRIV101_SURVEY_PROMPTS = [
  "Name something people do to relax after a long day.",
  "Name a food that's messy to eat on a first date.",
  "Name something you always forget to pack for a trip.",
  "Name a chore nobody likes doing.",
  "Name something people keep in their car but rarely use.",
  "Name a reason someone might be running late to work.",
  "Name something you'd find in a junk drawer.",
  "Name a topic you should avoid at family dinner.",
  "Name something people pretend to like just to be polite.",
  "Name a sound that instantly annoys you.",
  "Name something you do more when nobody's watching.",
  "Name a food that tastes better the next day.",
  "Name something people stretch the truth about on a resume.",
  "Name a place you'd hate to lose your phone.",
  "Name something a dog does that a cat never would.",
  "Name something people overpack for a weekend trip.",
  "Name a reason you'd return a gift.",
  "Name a drink that's way cheaper at the store than at a bar.",
  "Name a bad habit people try to quit every New Year.",
  "Name something you should never microwave.",
  "Name a smell that reminds you of childhood.",
  "Name something people do while stopped at a red light.",
  "Name a movie snack you can't live without.",
  "Name something that ruins a good camping trip.",
  "Name a reason people give for leaving a party early.",
  "Name something you'd find in a teenager's bedroom.",
  "Name a job that takes a lot of patience.",
  "Name something people are afraid to admit they've never done.",
  "Name a food that's surprisingly hard to eat neatly.",
  "Name something you'd grab first if the house was on fire.",
  "Name a reason a first date might go badly.",
  "Name something people collect that others think is junk.",
  "Name a household item that always goes missing.",
  "Name something you do to avoid small talk.",
  "Name a drink people order to look sophisticated.",
  "Name something that's better homemade than store-bought.",
  "Name a reason someone might get kicked out of a bar.",
  "Name something people fake being sick to get out of.",
  "Name a body part people injure doing something silly.",
  "Name something you'd never buy used.",
  "Name a food that's a total guilty pleasure.",
  "Name something people do way too much on social media.",
  "Name a reason your Wi-Fi might suddenly stop working.",
  "Name a song that always ends up on a road trip playlist.",
  "Name a task people put off until the last minute.",
  "Name something a bad tipper does.",
  "Name a place that's way too loud.",
  "Name something people say when they're clearly lying.",
  "Name a thing you'd find at every backyard barbecue.",
  "Name something you should never say to your boss.",
  "Name a reason people keep the receipt.",
  "Name something that's impossible to fold neatly.",
  "Name a snack you eat straight out of the bag.",
  "Name something people do when they're bored at work.",
  "Name a reason someone might cry at a wedding.",
  "Name something you'd always find in a hotel room.",
  "Name a food that's better at 2am than any other time.",
  "Name something people are weirdly competitive about.",
  "Name a thing you always lose at the beach.",
  "Name something people swear they'll do “tomorrow.”",
  "Name a reason a road trip gets delayed.",
  "Name something you'd find in a grandma's purse.",
  "Name a phrase that's overused in job interviews.",
  "Name something people secretly Google.",
  "Name a food you'd never share, even with family.",
  "Name something that's louder than it needs to be.",
  "Name a reason people avoid answering the phone.",
  "Name something you'd find at the bottom of a backpack.",
  "Name a thing that's always broken at the gym.",
  "Name something people do to look busy.",
  "Name a reason someone might get pulled over.",
  "Name something people regret buying at 3am online.",
  "Name a topping that's a dealbreaker on a pizza.",
  "Name something people bring to a potluck when they didn't cook.",
  "Name a thing that's harder than it looks.",
  "Name something you'd find in a “man cave.”",
  "Name a reason people leave a bad review.",
  "Name something that's always sticky at a movie theater.",
  "Name a chore kids try to get out of.",
  "Name something people brag about that isn't actually impressive.",
  "Name a drink that's a bad idea before noon.",
  "Name something in a first-aid kit that people use for something else.",
  "Name a reason someone might fake a phone call.",
  "Name something that ruins a nice photo.",
  "Name a food people eat way too fast.",
  "Name something you'd never microwave at the office.",
  "Name a reason people leave the group chat.",
  "Name something that's always warm when it shouldn't be.",
  "Name a book people say they've read but haven't.",
  "Name something you'd find in a dive bar bathroom.",
  "Name a reason someone might miss their flight.",
  "Name something people keep way past its expiration date.",
  "Name a hobby that sounds relaxing but isn't.",
  "Name something you'd find in a college dorm.",
  "Name a thing that always spills inside your bag.",
  "Name something people do to avoid going to the gym.",
  "Name a reason a night out gets cut short.",
  "Name something you'd find at a gas station at midnight.",
  "Name a food that's better on a stick.",
  "Name something everyone pretends to understand but doesn't."
];
