#!/usr/bin/env node
/**
 * Green Room seed — turns seed/threads.json into SQL for D1.
 *
 *   node greenroom-api/seed/seed.js            # check only, prints what it found
 *   node greenroom-api/seed/seed.js --write    # write seed/0002_seed.sql
 *
 * It REFUSES to emit SQL while any [OWNER: ...] placeholder survives in a
 * thread marked "launch": true. Same guard _tools/publish-post.js uses for
 * unresolved [bracket links], and for the same reason: the go-first mechanic
 * only works if what's behind it is real. A pinned question that asks people
 * to disclose their pay, above a Fat City post that discloses nothing, kills
 * the thread on day one.
 *
 * Re-running is safe. Pinned comments use a deterministic id (pin-<thread>)
 * and are upserted; unlocks for a thread are replaced wholesale.
 */

const fs = require("fs");
const path = require("path");

const DIR = __dirname;
const SRC = path.join(DIR, "threads.json");
const OUT = path.join(DIR, "0002_seed.sql");
const OUT_CONSOLE = path.join(DIR, "0002_seed.console.sql");
const write = process.argv.includes("--write");

/**
 * Strip `--` comments for the Cloudflare dashboard's D1 console, which drops
 * them and then errors with "Requests without any query are not supported".
 *
 * Comment markers inside a quoted string are left alone — the seed carries
 * Fat City's pinned pricing text, and cutting into that would corrupt it
 * silently rather than loudly.
 */
function stripComments(src) {
  const out = [];
  for (const line of src.split("\n")) {
    let inStr = false;
    let cut = -1;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (ch === "'") {
        if (inStr && line[i + 1] === "'") { i++; continue; } // '' escape
        inStr = !inStr;
      } else if (!inStr && ch === "-" && line[i + 1] === "-") { cut = i; break; }
    }
    const kept = (cut >= 0 ? line.slice(0, cut) : line).replace(/\s+$/, "");
    if (kept.trim()) out.push(kept);
  }
  return out.join("\n") + "\n";
}

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const PLACEHOLDER = /\[OWNER:/;

function main() {
  const doc = JSON.parse(fs.readFileSync(SRC, "utf8"));
  const threads = doc.threads || [];
  const live = threads.filter((t) => t.launch);

  if (!live.length) {
    console.error('Nothing to seed — no thread has "launch": true.');
    process.exit(1);
  }

  // --- the guard -----------------------------------------------------------
  const unresolved = [];
  for (const t of live) {
    if (PLACEHOLDER.test(t.pinned?.body || "")) {
      unresolved.push(`  ${t.key}: pinned question body`);
    }
    (t.unlocks || []).forEach((u, i) => {
      if (PLACEHOLDER.test(u)) unresolved.push(`  ${t.key}: unlock ${i + 1}`);
    });
    if (!(t.unlocks || []).length) {
      unresolved.push(`  ${t.key}: no unlocks at all (needs 3-4)`);
    }
  }

  console.log(`Threads to seed: ${live.map((t) => t.key).join(", ")}`);
  console.log(`Configured but not launching: ${
    threads.filter((t) => !t.launch).map((t) => t.key).join(", ") || "none"
  }`);

  if (unresolved.length) {
    console.error("\nRefusing to seed. Unresolved owner content:\n");
    console.error(unresolved.join("\n"));
    console.error(`
Fix these in ${path.relative(process.cwd(), SRC)} and run again.

The two things this is protecting:
  1. The Fat City disclosure. The room is being asked to name real numbers.
     It has to see us go first or the whole premise is hollow.
  2. The unlocks. They are drafts written to show the shape — confirm each
     one is true and ours to give, or replace it. An unlock that oversells
     reads as bait-and-switch and does more damage than no unlock at all.
`);
    process.exit(2);
  }

  // --- emit ----------------------------------------------------------------
  const lines = [
    "-- The Green Room — seed content.",
    "-- GENERATED by seed/seed.js from seed/threads.json. Do not hand-edit;",
    "-- edit the JSON and re-run. Safe to run more than once.",
    "",
  ];

  for (const t of live) {
    const p = t.pinned;
    const body = p.question + "\n\n" + p.body;
    const pid = "pin-" + t.key;

    lines.push(`-- ${t.key} (${t.surface})`);
    lines.push(
      "INSERT INTO comments (id, thread, parent_id, handle, role_tag, market, body, votes, flags, status, ip_hash, created_at)",
      `VALUES (${q(pid)}, ${q(t.key)}, NULL, ${q(p.handle)}, ${q(p.role_tag)}, NULL, ${q(body)}, 0, 0, 'pinned', NULL, strftime('%s','now')*1000)`,
      "ON CONFLICT(id) DO UPDATE SET body = excluded.body, handle = excluded.handle,",
      "  role_tag = excluded.role_tag, status = 'pinned';",
      ""
    );

    lines.push(`DELETE FROM unlocks WHERE thread = ${q(t.key)};`);
    for (const u of t.unlocks) {
      if (u.length > 400) {
        console.error(`\nUnlock too long in "${t.key}" (${u.length} chars, cap is 400):\n  ${u.slice(0, 80)}…`);
        process.exit(3);
      }
      lines.push(`INSERT INTO unlocks (thread, body) VALUES (${q(t.key)}, ${q(u)});`);
    }
    lines.push("");
  }

  const sql = lines.join("\n");

  if (!write) {
    console.log("\nAll owner content resolved. Re-run with --write to emit SQL.");
    console.log(`Would write ${sql.split("\n").length} lines to ${path.relative(process.cwd(), OUT)}`);
    return;
  }

  fs.writeFileSync(OUT, sql);
  console.log(`\nWrote ${path.relative(process.cwd(), OUT)}`);

  /* The D1 console in the Cloudflare dashboard strips `--` comments and then
     rejects what's left with "Requests without any query are not supported".
     wrangler handles the commented file fine; the dashboard does not. So emit
     a second, comment-free copy for pasting. */
  fs.writeFileSync(OUT_CONSOLE, stripComments(sql));
  console.log(`Wrote ${path.relative(process.cwd(), OUT_CONSOLE)}  (paste this one into the dashboard)`);

  console.log("\nApply it with the D1 console in the Cloudflare dashboard, or:");
  console.log("  npx wrangler d1 execute greenroom --remote --file=greenroom-api/seed/0002_seed.sql");
}

main();
