-- Seed: survey prompt pool (source=seed, status=surveying)
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-001','Name something people do to relax after a long day.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-002','Name a food that''s messy to eat on a first date.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-003','Name something you always forget to pack for a trip.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-004','Name a chore nobody likes doing.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-005','Name something people keep in their car but rarely use.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-006','Name a reason someone might be running late to work.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-007','Name something you''d find in a junk drawer.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-008','Name a topic you should avoid at family dinner.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-009','Name something people pretend to like just to be polite.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-010','Name a sound that instantly annoys you.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-011','Name something you do more when nobody''s watching.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-012','Name a food that tastes better the next day.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-013','Name something people stretch the truth about on a resume.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-014','Name a place you''d hate to lose your phone.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-015','Name something a dog does that a cat never would.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-016','Name something people overpack for a weekend trip.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-017','Name a reason you''d return a gift.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-018','Name a drink that''s way cheaper at the store than at a bar.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-019','Name a bad habit people try to quit every New Year.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-020','Name something you should never microwave.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-021','Name a smell that reminds you of childhood.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-022','Name something people do while stopped at a red light.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-023','Name a movie snack you can''t live without.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-024','Name something that ruins a good camping trip.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-025','Name a reason people give for leaving a party early.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-026','Name something you''d find in a teenager''s bedroom.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-027','Name a job that takes a lot of patience.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-028','Name something people are afraid to admit they''ve never done.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-029','Name a food that''s surprisingly hard to eat neatly.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-030','Name something you''d grab first if the house was on fire.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-031','Name a reason a first date might go badly.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-032','Name something people collect that others think is junk.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-033','Name a household item that always goes missing.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-034','Name something you do to avoid small talk.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-035','Name a drink people order to look sophisticated.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-036','Name something that''s better homemade than store-bought.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-037','Name a reason someone might get kicked out of a bar.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-038','Name something people fake being sick to get out of.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-039','Name a body part people injure doing something silly.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-040','Name something you''d never buy used.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-041','Name a food that''s a total guilty pleasure.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-042','Name something people do way too much on social media.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-043','Name a reason your Wi-Fi might suddenly stop working.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-044','Name a song that always ends up on a road trip playlist.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-045','Name a task people put off until the last minute.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-046','Name something a bad tipper does.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-047','Name a place that''s way too loud.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-048','Name something people say when they''re clearly lying.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-049','Name a thing you''d find at every backyard barbecue.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-050','Name something you should never say to your boss.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-051','Name a reason people keep the receipt.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-052','Name something that''s impossible to fold neatly.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-053','Name a snack you eat straight out of the bag.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-054','Name something people do when they''re bored at work.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-055','Name a reason someone might cry at a wedding.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-056','Name something you''d always find in a hotel room.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-057','Name a food that''s better at 2am than any other time.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-058','Name something people are weirdly competitive about.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-059','Name a thing you always lose at the beach.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-060','Name something people swear they''ll do “tomorrow.”','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-061','Name a reason a road trip gets delayed.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-062','Name something you''d find in a grandma''s purse.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-063','Name a phrase that''s overused in job interviews.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-064','Name something people secretly Google.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-065','Name a food you''d never share, even with family.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-066','Name something that''s louder than it needs to be.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-067','Name a reason people avoid answering the phone.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-068','Name something you''d find at the bottom of a backpack.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-069','Name a thing that''s always broken at the gym.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-070','Name something people do to look busy.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-071','Name a reason someone might get pulled over.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-072','Name something people regret buying at 3am online.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-073','Name a topping that''s a dealbreaker on a pizza.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-074','Name something people bring to a potluck when they didn''t cook.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-075','Name a thing that''s harder than it looks.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-076','Name something you''d find in a “man cave.”','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-077','Name a reason people leave a bad review.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-078','Name something that''s always sticky at a movie theater.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-079','Name a chore kids try to get out of.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-080','Name something people brag about that isn''t actually impressive.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-081','Name a drink that''s a bad idea before noon.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-082','Name something in a first-aid kit that people use for something else.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-083','Name a reason someone might fake a phone call.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-084','Name something that ruins a nice photo.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-085','Name a food people eat way too fast.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-086','Name something you''d never microwave at the office.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-087','Name a reason people leave the group chat.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-088','Name something that''s always warm when it shouldn''t be.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-089','Name a book people say they''ve read but haven''t.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-090','Name something you''d find in a dive bar bathroom.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-091','Name a reason someone might miss their flight.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-092','Name something people keep way past its expiration date.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-093','Name a hobby that sounds relaxing but isn''t.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-094','Name something you''d find in a college dorm.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-095','Name a thing that always spills inside your bag.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-096','Name something people do to avoid going to the gym.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-097','Name a reason a night out gets cut short.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-098','Name something you''d find at a gas station at midnight.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-099','Name a food that''s better on a stick.','seed','surveying', strftime('%s','now')*1000);
INSERT OR IGNORE INTO prompts (id,text,source,status,created_at) VALUES ('seed-100','Name something everyone pretends to understand but doesn''t.','seed','surveying', strftime('%s','now')*1000);
